# Generated by Django 3.2.7 on 2023-04-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190904_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detected',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
